export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const SAVE_CATEGORIES_TO_STORE = 'SAVE_CATEGORIES_TO_STORE';
export const INIT_CATEGORIES_DATA = 'INIT_CATEGORIES_DATA';
export const APPLY_DEMO_CATEGORIES = 'APPLY_DEMO_CATEGORIES';
export const APPLY_NEW_CATEGORIES = 'APPLY_NEW_CATEGORIES';